function Database_POI()
	return {
		-- playlist 1
		{	PlaylistName = "Legacy Korean exclusives",
			Banner = "Playlists/001-legacykor.png",
			Description = "Description for -Legacy Korean exclusives-",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "Exclusive charts from Pump It Up The 2nd Dance Floor",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "2ND-DOUBLE" } },
					},
				},
			-- sublist 2
				{	SublistName = "Exclusive charts from Pump It Up O.B.G The 3rd Dance Floor",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "3RD-NORMAL", "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "3RD-DOUBLE" } },
					},
				},
			-- sublist 3
				{	SublistName = "Exclusive charts from Pump It Up O.B.G Season Evolution",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/408 - KISS/", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
					},
				},
			-- sublist 4
				{	SublistName = "Exclusive charts from Pump It Up Extra",
					StartingSong = 7,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/904 - TRASH MAN/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/923 - FIRST LOVE (TECHNO MIX)/", Charts = { "EXTRA-XXPERT", "EXTRA-XXDOUBLE" } },
					},
				},
			-- sublist 5
				{	SublistName = "Exclusive Korean remixes",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/116 - -REMIX- 1ST DIVA REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/117 - -REMIX- 1ST DISCO REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/118 - -REMIX- 1ST TECHNO REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/219 - -REMIX- JO SUNG MO REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/220 - -REMIX- UHM JUNG HWA REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/223 - -REMIX- SM TOWN REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/224 - -REMIX- REPEATORMENT REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/225 - -REMIX- 2ND HIDDEN REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/322 - -REMIX- 3RD O.B.G DIVA REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/323 - -REMIX- PARK MEE KYUNG REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/325 - -REMIX- PARK JIN YOUNG REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/327 - -REMIX- BANYA HARD REMIX/", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/415 - -REMIX- SECHSKIES REMIX/", Charts = { "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/924 - -REMIX- EXTRA HIP-HOP REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/925 - -REMIX- E-PAK-SA REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/926 - -REMIX- EXTRA DISCO REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/927 - -REMIX- EXTRA DEUX REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
					},
				},
			},
		},
		-- playlist 2
		{	PlaylistName = "Premiere Brazil exclusives",
			Banner = "Playlists/002-premierebr.png",
			Description = "Description for -Premiere Brazil exclusives-",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "NORMAL charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-NORMAL" } },
					},
				},
			-- sublist 2
				{	SublistName = "HARD charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-HARD" } },
					},
				},
			-- sublist 3
				{	SublistName = "DOUBLE charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-DOUBLE" } },
					},
				},
			},
		},
		-- playlist 3
		{	PlaylistName = "Exceed S.E exclusives",
			Banner = "Playlists/003-exceedse.png",
			Description = "Description for -Exceed S.E exclusives-",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "NORMAL charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-NORMAL" } },
					},
				},
			-- sublist 2
				{	SublistName = "HARD charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-HARD" } },
					},
				},
			-- sublist 3
				{	SublistName = "CRAZY charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-CRAZY" } },
					},
				},
			-- sublist 4
				{	SublistName = "FREESTYLE charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-FREESTYLE" } },
					},
				},
			-- sublist 5
				{	SublistName = "NIGHTMARE charts",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-NIGHTMARE" } },
					},
				},
			},
		},
		-- playlist 4
		{	PlaylistName = "Cutting room floor",
			Banner = "Playlists/004-cuttingroom.png",
			Description = "Description for -Cutting room floor-",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "Cut charts from Pump It Up The Prex 3",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/828 - MASTER OF PUPPETS/", Charts = { "PREX3-NORMAL", "PREX3-HARD", "PREX3-CRAZY", "PREX3-HALFDOUBLE", "PREX3-FREESTYLE", "PREX3-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/822 - JUST A GIRL/", Charts = { "PREX3-NORMAL", "PREX3-HARD", "PREX3-CRAZY", "PREX3-HALFDOUBLE", "PREX3-FREESTYLE", "PREX3-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/824 - OBJECTION/", Charts = { "PREX3-NORMAL", "PREX3-HARD", "PREX3-CRAZY", "PREX3-HALFDOUBLE", "PREX3-FREESTYLE", "PREX3-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/825 - IT'S MY PARTY/", Charts = { "PREX3-NORMAL", "PREX3-HARD", "PREX3-CRAZY", "PREX3-HALFDOUBLE", "PREX3-FREESTYLE", "PREX3-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/827 - MUSIC/", Charts = { "PREX3-NORMAL", "PREX3-HARD", "PREX3-CRAZY", "PREX3-HALFDOUBLE", "PREX3-FREESTYLE", "PREX3-NIGHTMARE" } },
					},
				},
			},
		},
		-- playlist 5
		{	PlaylistName = "Pump It Up The Prex",
			Banner = "Playlists/08-prex.png",
			Description = "Description for -Pump It Up The Prex-\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris\nnisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in\nreprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "NORMAL charts",
					StartingSong = 75,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/103 - FOREVER LOVE/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/107 - THE RAP/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/110 - WHAT DO U REALLY WANT/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/113 - I WANT U/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/114 - I DON'T KNOW ANYTHING/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/115 - NO PARTICULAR REASON/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/201 - CREAMY SKINNY/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/206 - REWIND/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/208 - FIGHTING SPIRITS/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/210 - LOVE/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/218 - HEART BREAK/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/304 - WITH MY LOVER/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/308 - FREE STYLE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/314 - LOVER'S GRIEF/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/315 - TO THE TOP/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/317 - PUYO PUYO/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/321 - OK OK (BEAUTY AND THE BEAST)/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-NORMAL" } },
					},
				},
			-- sublist 2
				{	SublistName = "HARD charts",
					StartingSong = 82,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/105 - BLACK CAT/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/109 - FUNKY TONIGHT/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/111 - HATRED/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/203 - KOUL/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/207 - I-YAH/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/211 - PLEASE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/212 - COM'BACK/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/213 - MOBIUS STRIP/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/216 - LOVE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/218 - HEART BREAK/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/305 - AN INTERESTING VIEW/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/309 - MIDNIGHT BLUE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/311 - PUMPING UP/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/315 - TO THE TOP/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/318 - WE ARE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/320 - TELL ME/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/902 - CIRCUS MAGIC/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/906 - STARIAN/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-HARD" } },
					},
				},
			-- sublist 3
				{	SublistName = "CRAZY charts",
					StartingSong = 39,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/305 - AN INTERESTING VIEW/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/904 - TRASH MAN/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/911 - CHICKEN WING/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/912 - HOLIDAY/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/913 - RADEZKY CAN CAN/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-XXPERT" } },
					},
				},
			-- sublist 4
				{	SublistName = "DOUBLE charts",
					StartingSong = 82,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/105 - BLACK CAT/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/109 - FUNKY TONIGHT/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/111 - HATRED/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/113 - I WANT U/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/114 - I DON'T KNOW ANYTHING/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/115 - NO PARTICULAR REASON/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/201 - CREAMY SKINNY/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/203 - KOUL/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/207 - I-YAH/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/208 - FIGHTING SPIRITS/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/211 - PLEASE/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/213 - MOBIUS STRIP/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/308 - FREE STYLE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/309 - MIDNIGHT BLUE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/314 - LOVER'S GRIEF/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/317 - PUYO PUYO/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/318 - WE ARE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/321 - OK OK (BEAUTY AND THE BEAST)/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/902 - CIRCUS MAGIC/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/906 - STARIAN/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/911 - CHICKEN WING/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/912 - HOLIDAY/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/913 - RADEZKY CAN CAN/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-DOUBLE" } },
					},
				},
			-- sublist 5
				{	SublistName = "Progressive level: SINGLES",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/308 - FREE STYLE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/103 - FOREVER LOVE/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/107 - THE RAP/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/113 - I WANT U/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/208 - FIGHTING SPIRITS/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/210 - LOVE/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/314 - LOVER'S GRIEF/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/114 - I DON'T KNOW ANYTHING/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/206 - REWIND/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/218 - HEART BREAK/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/304 - WITH MY LOVER/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/315 - TO THE TOP/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/317 - PUYO PUYO/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/110 - WHAT DO U REALLY WANT/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/115 - NO PARTICULAR REASON/", Charts = { "1ST-NORMAL" } },
						{ SongPath = "/Songs/POI-database/201 - CREAMY SKINNY/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-NORMAL" } },
						{ SongPath = "/Songs/POI-database/321 - OK OK (BEAUTY AND THE BEAST)/", Charts = { "3RD-NORMAL" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-NORMAL" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/109 - FUNKY TONIGHT/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/207 - I-YAH/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/309 - MIDNIGHT BLUE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-NORMAL" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/216 - LOVE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/218 - HEART BREAK/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/311 - PUMPING UP/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/318 - WE ARE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/320 - TELL ME/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/105 - BLACK CAT/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/111 - HATRED/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/203 - KOUL/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/211 - PLEASE/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/212 - COM'BACK/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/213 - MOBIUS STRIP/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/305 - AN INTERESTING VIEW/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "2ND-HARD" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/315 - TO THE TOP/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/906 - STARIAN/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-HARD" } },
						{ SongPath = "/Songs/POI-database/902 - CIRCUS MAGIC/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-HARD" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/911 - CHICKEN WING/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-HARD" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/305 - AN INTERESTING VIEW/", Charts = { "3RD-CRAZY" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-CRAZY" } },
						{ SongPath = "/Songs/POI-database/904 - TRASH MAN/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/912 - HOLIDAY/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/913 - RADEZKY CAN CAN/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-XXPERT" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-CRAZY" } },
					},
				},
			-- sublist 6
				{	SublistName = "Progressive level: DOUBLES",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/308 - FREE STYLE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/109 - FUNKY TONIGHT/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/113 - I WANT U/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/114 - I DON'T KNOW ANYTHING/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/115 - NO PARTICULAR REASON/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/317 - PUYO PUYO/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/502 - N/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/201 - CREAMY SKINNY/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/202 - HATE/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/208 - FIGHTING SPIRITS/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/211 - PLEASE/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/309 - MIDNIGHT BLUE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/314 - LOVER'S GRIEF/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/321 - OK OK (BEAUTY AND THE BEAST)/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/104 - PASSION/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/207 - I-YAH/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/318 - WE ARE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/105 - BLACK CAT/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/111 - HATRED/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/203 - KOUL/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/213 - MOBIUS STRIP/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", Charts = { "1ST-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/902 - CIRCUS MAGIC/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/906 - STARIAN/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", Charts = { "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "PERF-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/911 - CHICKEN WING/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/912 - HOLIDAY/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/913 - RADEZKY CAN CAN/", Charts = { "EXTRA-XXDOUBLE" } },
					},
				},
			},
		},
		-- playlist 6
		{	PlaylistName = "All Tunes",
			Banner = "Playlists/999-alltunes.png",
			Description = "This lists all songs, without any filtering",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	SublistName = "All Tunes",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/101 - IGNITION STARTS/", },
						{ SongPath = "/Songs/POI-database/102 - HYPNOSIS/", },
						{ SongPath = "/Songs/POI-database/103 - FOREVER LOVE/", },
						{ SongPath = "/Songs/POI-database/104 - PASSION/", },
						{ SongPath = "/Songs/POI-database/105 - BLACK CAT/", },
						{ SongPath = "/Songs/POI-database/106 - POM POM POM/", },
						{ SongPath = "/Songs/POI-database/107 - THE RAP/", },
						{ SongPath = "/Songs/POI-database/108 - COME TO ME/", },
						{ SongPath = "/Songs/POI-database/109 - FUNKY TONIGHT/", },
						{ SongPath = "/Songs/POI-database/110 - WHAT DO U REALLY WANT/", },
						{ SongPath = "/Songs/POI-database/111 - HATRED/", },
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", },
						{ SongPath = "/Songs/POI-database/113 - I WANT U/", },
						{ SongPath = "/Songs/POI-database/114 - I DON'T KNOW ANYTHING/", },
						{ SongPath = "/Songs/POI-database/115 - NO PARTICULAR REASON/", },
						{ SongPath = "/Songs/POI-database/116 - -REMIX- 1ST DIVA REMIX/", },
						{ SongPath = "/Songs/POI-database/117 - -REMIX- 1ST DISCO REMIX/", },
						{ SongPath = "/Songs/POI-database/118 - -REMIX- 1ST TECHNO REMIX/", },
						{ SongPath = "/Songs/POI-database/119 - -REMIX- TURBO REMIX/", },
						{ SongPath = "/Songs/POI-database/201 - CREAMY SKINNY/", },
						{ SongPath = "/Songs/POI-database/202 - HATE/", },
						{ SongPath = "/Songs/POI-database/203 - KOUL/", },
						{ SongPath = "/Songs/POI-database/204 - FINAL AUDITION/", },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", },
						{ SongPath = "/Songs/POI-database/206 - REWIND/", },
						{ SongPath = "/Songs/POI-database/207 - I-YAH/", },
						{ SongPath = "/Songs/POI-database/208 - FIGHTING SPIRITS/", },
						{ SongPath = "/Songs/POI-database/210 - LOVE/", },
						{ SongPath = "/Songs/POI-database/211 - PLEASE/", },
						{ SongPath = "/Songs/POI-database/212 - COM'BACK/", },
						{ SongPath = "/Songs/POI-database/213 - MOBIUS STRIP/", },
						{ SongPath = "/Songs/POI-database/214 - FEVER/", },
						{ SongPath = "/Songs/POI-database/215 - CURIOSITY/", },
						{ SongPath = "/Songs/POI-database/216 - LOVE/", },
						{ SongPath = "/Songs/POI-database/217 - TELL ME TELL ME/", },
						{ SongPath = "/Songs/POI-database/218 - HEART BREAK/", },
						{ SongPath = "/Songs/POI-database/219 - -REMIX- JO SUNG MO REMIX/", },
						{ SongPath = "/Songs/POI-database/220 - -REMIX- UHM JUNG HWA REMIX/", },
						{ SongPath = "/Songs/POI-database/221 - -REMIX- DRUNKEN FAMILY REMIX/", },
						{ SongPath = "/Songs/POI-database/223 - -REMIX- SM TOWN REMIX/", },
						{ SongPath = "/Songs/POI-database/224 - -REMIX- REPEATORMENT REMIX/", },
						{ SongPath = "/Songs/POI-database/225 - -REMIX- 2ND HIDDEN REMIX/", },
						{ SongPath = "/Songs/POI-database/301 - FINAL AUDITION 2/", },
						{ SongPath = "/Songs/POI-database/302 - NAISSANCE/", },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", },
						{ SongPath = "/Songs/POI-database/304 - WITH MY LOVER/", },
						{ SongPath = "/Songs/POI-database/305 - AN INTERESTING VIEW/", },
						{ SongPath = "/Songs/POI-database/306 - NIGHTMARE/", },
						{ SongPath = "/Songs/POI-database/307 - CLOSE YOUR EYES/", },
						{ SongPath = "/Songs/POI-database/308 - FREE STYLE/", },
						{ SongPath = "/Songs/POI-database/309 - MIDNIGHT BLUE/", },
						{ SongPath = "/Songs/POI-database/310 - SHE LIKES PIZZA/", },
						{ SongPath = "/Songs/POI-database/311 - PUMPING UP/", },
						{ SongPath = "/Songs/POI-database/312 - DON'T BOTHER ME/", },
						{ SongPath = "/Songs/POI-database/313 - LOVE SONG/", },
						{ SongPath = "/Songs/POI-database/314 - LOVER'S GRIEF/", },
						{ SongPath = "/Songs/POI-database/315 - TO THE TOP/", },
						{ SongPath = "/Songs/POI-database/316 - SEPARATION WITH HER/", },
						{ SongPath = "/Songs/POI-database/317 - PUYO PUYO/", },
						{ SongPath = "/Songs/POI-database/318 - WE ARE/", },
						{ SongPath = "/Songs/POI-database/319 - TIME TO SAY GOODBYE/", },
						{ SongPath = "/Songs/POI-database/320 - TELL ME/", },
						{ SongPath = "/Songs/POI-database/321 - OK OK (BEAUTY AND THE BEAST)/", },
						{ SongPath = "/Songs/POI-database/322 - -REMIX- 3RD O.B.G DIVA REMIX/", },
						{ SongPath = "/Songs/POI-database/323 - -REMIX- PARK MEE KYUNG REMIX/", },
						{ SongPath = "/Songs/POI-database/324 - -REMIX- BANYA HIP-HOP REMIX/", },
						{ SongPath = "/Songs/POI-database/325 - -REMIX- PARK JIN YOUNG REMIX/", },
						{ SongPath = "/Songs/POI-database/326 - -REMIX- NOVASONIC REMIX/", },
						{ SongPath = "/Songs/POI-database/327 - -REMIX- BANYA HARD REMIX/", },
						{ SongPath = "/Songs/POI-database/401 - OH! ROSA/", },
						{ SongPath = "/Songs/POI-database/402 - FIRST LOVE/", },
						{ SongPath = "/Songs/POI-database/403 - BETRAYER/", },
						{ SongPath = "/Songs/POI-database/404 - SOLITARY/", },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", },
						{ SongPath = "/Songs/POI-database/406 - SAD SALSA/", },
						{ SongPath = "/Songs/POI-database/407 - SUMMER OF LOVE/", },
						{ SongPath = "/Songs/POI-database/408 - KISS/", },				
						{ SongPath = "/Songs/POI-database/409 - MAN & WOMAN/", },
						{ SongPath = "/Songs/POI-database/410 - FIRST LOVE/", },
						{ SongPath = "/Songs/POI-database/411 - A TRAP/", },
						{ SongPath = "/Songs/POI-database/412 - DISCO BUS/", },
						{ SongPath = "/Songs/POI-database/413 - RUN!/", },
						{ SongPath = "/Songs/POI-database/414 - RUN TO YOU/", },
						{ SongPath = "/Songs/POI-database/415 - -REMIX- SECHSKIES REMIX/", },
						{ SongPath = "/Songs/POI-database/501 - PUMP JUMP/", },
						{ SongPath = "/Songs/POI-database/502 - N/", },
						{ SongPath = "/Songs/POI-database/503 - ROLLING CHRISTMAS/", },
						{ SongPath = "/Songs/POI-database/504 - ALL I WANT FOR X-MAS/", },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", },
						{ SongPath = "/Songs/POI-database/506 - I WILL ACCEPT YOU/", },
						{ SongPath = "/Songs/POI-database/507 - COME BACK TO ME/", },
						{ SongPath = "/Songs/POI-database/508 - AS I TOLD YOU/", },
						{ SongPath = "/Songs/POI-database/509 - I KNOW/", },
						{ SongPath = "/Songs/POI-database/510 - MY FANTASY/", },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", },
						{ SongPath = "/Songs/POI-database/512 - HAYUGA/", },
						{ SongPath = "/Songs/POI-database/513 - CERTAIN VICTORY/", },
						{ SongPath = "/Songs/POI-database/514 - ULTRAMANIA/", },
						{ SongPath = "/Songs/POI-database/515 - BONACCIA/", },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", },
						{ SongPath = "/Songs/POI-database/517 - SPACE FANTASY/", },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", },
						{ SongPath = "/Songs/POI-database/911 - CHICKEN WING/", },
						{ SongPath = "/Songs/POI-database/912 - HOLIDAY/", },
						{ SongPath = "/Songs/POI-database/913 - RADEZKY CAN CAN/", },
						{ SongPath = "/Songs/POI-database/901 - FLOWER OF NIGHT/", },
						{ SongPath = "/Songs/POI-database/902 - CIRCUS MAGIC/", },
						{ SongPath = "/Songs/POI-database/903 - MOVE YOUR HEAD/", },
						{ SongPath = "/Songs/POI-database/904 - TRASH MAN/", },
						{ SongPath = "/Songs/POI-database/919 - LAZENCA, SAVE US/", },
						{ SongPath = "/Songs/POI-database/905 - FUNKY JOCKEY/", },
						{ SongPath = "/Songs/POI-database/906 - STARIAN/", },
						{ SongPath = "/Songs/POI-database/907 - BIG MONEY/", },
						{ SongPath = "/Songs/POI-database/908 - WAYO WAYO/", },
						{ SongPath = "/Songs/POI-database/909 - MISTAKE/", },
						{ SongPath = "/Songs/POI-database/910 - THE RAP ACT 3/", },
						{ SongPath = "/Songs/POI-database/914 - WISH YOU COULD FIND/", },
						{ SongPath = "/Songs/POI-database/915 - LONER/", },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", },
						{ SongPath = "/Songs/POI-database/917 - OUT OF THE RING/", },
						{ SongPath = "/Songs/POI-database/921 - PIERROT/", },
						{ SongPath = "/Songs/POI-database/918 - BLIND FAITH/", },
						{ SongPath = "/Songs/POI-database/920 - FERRY BOAT/", },
						{ SongPath = "/Songs/POI-database/923 - FIRST LOVE (TECHNO MIX)/", },
						{ SongPath = "/Songs/POI-database/924 - -REMIX- EXTRA HIP-HOP REMIX/", },
						{ SongPath = "/Songs/POI-database/925 - -REMIX- E-PAK-SA REMIX/", },
						{ SongPath = "/Songs/POI-database/926 - -REMIX- EXTRA DISCO REMIX/", },
						{ SongPath = "/Songs/POI-database/927 - -REMIX- EXTRA DEUX REMIX/", },
						{ SongPath = "/Songs/POI-database/928 - -REMIX- EXTRA BANYA MIX/", },
						{ SongPath = "/Songs/POI-database/601 - OOPS I DID IT AGAIN/", },
						{ SongPath = "/Songs/POI-database/602 - BYE BYE BYE/", },
						{ SongPath = "/Songs/POI-database/603 - I NEED TO KNOW/", },
						{ SongPath = "/Songs/POI-database/604 - LET'S GET LOUD/", },
						{ SongPath = "/Songs/POI-database/605 - MAMBO #5/", },
						{ SongPath = "/Songs/POI-database/606 - TAKE ON ME/", },
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", },
						{ SongPath = "/Songs/POI-database/735 - VOOK/", },
						{ SongPath = "/Songs/POI-database/736 - CSIKOS POST/", },
						{ SongPath = "/Songs/POI-database/701 - DR. M/", },
						{ SongPath = "/Songs/POI-database/702 - EMPEROR/", },
						{ SongPath = "/Songs/POI-database/703 - GET YOUR GROOVE ON/", },
						{ SongPath = "/Songs/POI-database/704 - LOVE IS A DANGER ZONE/", },
						{ SongPath = "/Songs/POI-database/705 - MARIA/", },
						{ SongPath = "/Songs/POI-database/706 - MISSION POSSIBLE/", },
						{ SongPath = "/Songs/POI-database/707 - MY WAY/", },
						{ SongPath = "/Songs/POI-database/708 - POINT BREAK/", },
						{ SongPath = "/Songs/POI-database/709 - STREET SHOW DOWN/", },
						{ SongPath = "/Songs/POI-database/710 - TOP CITY/", },
						{ SongPath = "/Songs/POI-database/711 - WINTER/", },
						{ SongPath = "/Songs/POI-database/712 - WILL O' THE WISP/", },
						{ SongPath = "/Songs/POI-database/713 - TILL THE END OF TIME/", },
						{ SongPath = "/Songs/POI-database/714 - OY OY OY/", },
						{ SongPath = "/Songs/POI-database/715 - WE WILL MEET AGAIN/", },
						{ SongPath = "/Songs/POI-database/716 - MISS'S STORY/", },
						{ SongPath = "/Songs/POI-database/717 - SET ME UP/", },
						{ SongPath = "/Songs/POI-database/718 - DANCE WITH ME/", },
						{ SongPath = "/Songs/POI-database/719 - GO AWAY/", },
						{ SongPath = "/Songs/POI-database/726 - RUNAWAY/", },
						{ SongPath = "/Songs/POI-database/720 - I LOVE YOU/", },
						{ SongPath = "/Songs/POI-database/721 - GOTTA BE KIDDING!/", },
						{ SongPath = "/Songs/POI-database/722 - ZZANGA/", },
						{ SongPath = "/Songs/POI-database/729 - Y/", },
						{ SongPath = "/Songs/POI-database/723 - A PRISON WITHOUT BARS/", },
						{ SongPath = "/Songs/POI-database/727 - SWING BABY/", },
						{ SongPath = "/Songs/POI-database/724 - A WHISTLE/", },
						{ SongPath = "/Songs/POI-database/725 - GENTLEMAN QUALITY/", },
						{ SongPath = "/Songs/POI-database/728 - TEMPTATION/", },
						{ SongPath = "/Songs/POI-database/730 - PERFECT!/", },
						{ SongPath = "/Songs/POI-database/731 - LET'S BOOGIE/", },
						{ SongPath = "/Songs/POI-database/732 - MY BEST DAY IS GONE/", },
						{ SongPath = "/Songs/POI-database/733 - THE WAVES/", },
						{ SongPath = "/Songs/POI-database/734 - ALWAYS/", },
						{ SongPath = "/Songs/POI-database/802 - BEE/", },
						{ SongPath = "/Songs/POI-database/807 - D GANG/", },
						{ SongPath = "/Songs/POI-database/811 - HELLO/", },
						{ SongPath = "/Songs/POI-database/820 - BEAT OF THE WAR/", },
						{ SongPath = "/Songs/POI-database/803 - BURNING KRYPT/", },
						{ SongPath = "/Songs/POI-database/804 - CAN YOU FEEL DIS OR DAT/", },
						{ SongPath = "/Songs/POI-database/808 - DJ NIGHTMARE/", },
						{ SongPath = "/Songs/POI-database/819 - YOU DON'T WANNA RUNUP/", },
						{ SongPath = "/Songs/POI-database/801 - BAMBOLE/", },
						{ SongPath = "/Songs/POI-database/805 - CLAP YOUR HANDS/", },
						{ SongPath = "/Songs/POI-database/806 - CONGA/", },
						{ SongPath = "/Songs/POI-database/809 - ERES PARA MI/", },
						{ SongPath = "/Songs/POI-database/818 - MEXI MEXI/", },
						{ SongPath = "/Songs/POI-database/810 - FIEST A MACARENA PT. 1/", },
						{ SongPath = "/Songs/POI-database/812 - ON YOUR SIDE/", },
						{ SongPath = "/Songs/POI-database/813 - EVERYBODY/", },
						{ SongPath = "/Songs/POI-database/814 - JOIN THE PARTY/", },
						{ SongPath = "/Songs/POI-database/815 - LAY IT DOWN/", },
						{ SongPath = "/Songs/POI-database/816 - LET THE SUNSHINE/", },
						{ SongPath = "/Songs/POI-database/817 - LOVETHING/", },
						{ SongPath = "/Songs/POI-database/826 - COME TO ME/", },
						{ SongPath = "/Songs/POI-database/821 - EMPIRE OF THE SUN/", },
						{ SongPath = "/Songs/POI-database/823 - LET'S GET THE PARTY STARTED/", },
						{ SongPath = "/Songs/POI-database/828 - MASTER OF PUPPETS/", },
						{ SongPath = "/Songs/POI-database/822 - JUST A GIRL/", },
						{ SongPath = "/Songs/POI-database/824 - OBJECTION/", },
						{ SongPath = "/Songs/POI-database/825 - IT'S MY PARTY/", },
						{ SongPath = "/Songs/POI-database/827 - MUSIC/", },
						{ SongPath = "/Songs/POI-database/A01 - FINAL AUDITION 3 U.F/", },
						{ SongPath = "/Songs/POI-database/A02 - NAISSANCE 2/", },
						{ SongPath = "/Songs/POI-database/A03 - MONKEY FINGERS/", },
						{ SongPath = "/Songs/POI-database/A04 - BLAZING/", },
						{ SongPath = "/Songs/POI-database/A05 - PUMP ME AMADEUS/", },
						{ SongPath = "/Songs/POI-database/A06 - X-TREAM/", },
						{ SongPath = "/Songs/POI-database/A07 - GET UP!/", },
						{ SongPath = "/Songs/POI-database/A26 - OH! ROSA (SPANISH VER.)/", },
						{ SongPath = "/Songs/POI-database/A27 - FIRST LOVE (SPANISH VER.)/", },
						{ SongPath = "/Songs/POI-database/A08 - DIGNITY/", },
						{ SongPath = "/Songs/POI-database/A11 - WHAT DO U REALLY WANT/", },
						{ SongPath = "/Songs/POI-database/A09 - SHAKE THAT BOOTIE/", },
						{ SongPath = "/Songs/POI-database/A10 - VALENTI/", },
						{ SongPath = "/Songs/POI-database/A12 - GO/", },
						{ SongPath = "/Songs/POI-database/A13 - FLAMENCO/", },
						{ SongPath = "/Songs/POI-database/A19 - ONE LOVE/", },
						{ SongPath = "/Songs/POI-database/A14 - KISS ME/", },
						{ SongPath = "/Songs/POI-database/A15 - ESSA MANEIRA/", },
						{ SongPath = "/Songs/POI-database/A16 - BA BEE LOO BE RA/", },
						{ SongPath = "/Songs/POI-database/A17 - LA CUBANITA/", },
						{ SongPath = "/Songs/POI-database/A18 - SHAKE IT UP/", },
						{ SongPath = "/Songs/POI-database/A20 - POWER OF DREAM/", },
						{ SongPath = "/Songs/POI-database/A21 - WATCH OUT/", },
						{ SongPath = "/Songs/POI-database/A22 - FIESTA/", },
						{ SongPath = "/Songs/POI-database/A23 - SOCA MAKE YUH RAM RAM/", },
						{ SongPath = "/Songs/POI-database/A24 - BORN TO BE ALIVE/", },
						{ SongPath = "/Songs/POI-database/A25 - XIBOM BOMBOM/", },
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", },
						{ SongPath = "/Songs/POI-database/B16 - J BONG/", },
						{ SongPath = "/Songs/POI-database/B17 - HI-BI/", },
						{ SongPath = "/Songs/POI-database/B18 - SOLITARY 2/", },
						{ SongPath = "/Songs/POI-database/B19 - CANON-D/", },
						{ SongPath = "/Songs/POI-database/B01 - GREENHORN/", },
						{ SongPath = "/Songs/POI-database/B02 - HOT/", },
						{ SongPath = "/Songs/POI-database/B03 - PRAY/", },
						{ SongPath = "/Songs/POI-database/B06 - DEJA VU/", },
						{ SongPath = "/Songs/POI-database/B04 - GO AWAY/", },
						{ SongPath = "/Songs/POI-database/B05 - DRUNKEN IN MELODY/", },
						{ SongPath = "/Songs/POI-database/B07 - U/", },
						{ SongPath = "/Songs/POI-database/B08 - SAJAHU (LION'S ROAR)/", },
						{ SongPath = "/Songs/POI-database/B09 - TYPHOON/", },
						{ SongPath = "/Songs/POI-database/B10 - ETERNITY/", },
						{ SongPath = "/Songs/POI-database/B11 - FOXY LADY/", },
						{ SongPath = "/Songs/POI-database/B12 - TOO LATE/", },
						{ SongPath = "/Songs/POI-database/B13 - I'LL GIVE YOU ALL MY LOVE/", },
						{ SongPath = "/Songs/POI-database/B14 - HUU YAH YEAH/", },
						{ SongPath = "/Songs/POI-database/B15 - WE DON'T STOP/", },
						{ SongPath = "/Songs/POI-database/B20 - LE CODE DE BONNE CONDUITE/", },
						{ SongPath = "/Songs/POI-database/B26 - -REMIX- NOVARASH REMIX/", },
						{ SongPath = "/Songs/POI-database/B27 - -REMIX- LEXY & 1TYM REMIX/", },
						{ SongPath = "/Songs/POI-database/B28 - -REMIX- TREAM-VOOK OF THE WAR/", },
						{ SongPath = "/Songs/POI-database/B29 - -REMIX- BANYA CLASSIC REMIX/", },
						{ SongPath = "/Songs/POI-database/B30 - -REMIX- DEUX REMIX/", },
						{ SongPath = "/Songs/POI-database/B31 - -REMIX- DIVA REMIX/", },
						{ SongPath = "/Songs/POI-database/B50 - -REMIX- THE WORLD REMIX/", },
						{ SongPath = "/Songs/POI-database/B51 - DIGNITY -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/B57 - CANON-D -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/1059 - EXCEED 2 OPENING -SHORT CUT-/", },
						{ SongPath = "/Songs/POI-database/C01 - BEAT OF THE WAR 2/", },
						{ SongPath = "/Songs/POI-database/C02 - MOONLIGHT/", },
						{ SongPath = "/Songs/POI-database/C03 - WITCH DOCTOR/", },
						{ SongPath = "/Songs/POI-database/C04 - LOVE IS A DANGER ZONE 2/", },
						{ SongPath = "/Songs/POI-database/DC04 - LOVE IS A DANGER ZONE 2 (D&G VER.)/", },
						{ SongPath = "/Songs/POI-database/C05 - PHANTOM/", },
						{ SongPath = "/Songs/POI-database/C06 - PAPA GONZALES/", },
						{ SongPath = "/Songs/POI-database/C07 - JUMP/", },
						{ SongPath = "/Songs/POI-database/C08 - EMERGENCY/", },
						{ SongPath = "/Songs/POI-database/C09 - MY FRIEND/", },
						{ SongPath = "/Songs/POI-database/C10 - WUTHERING HEIGHTS/", },
						{ SongPath = "/Songs/POI-database/C11 - DO IT YOURSELF/", },
						{ SongPath = "/Songs/POI-database/C12 - WHAT'S GOIN' ON/", },
						{ SongPath = "/Songs/POI-database/C13 - ALL FAMY/", },
						{ SongPath = "/Songs/POI-database/C14 - CHUNG HWA BAN JEOM/", },
						{ SongPath = "/Songs/POI-database/C15 - MR. FIRE FIGHTER/", },
						{ SongPath = "/Songs/POI-database/C16 - FOOTPRINTS/", },
						{ SongPath = "/Songs/POI-database/C17 - OH MY!/", },
						{ SongPath = "/Songs/POI-database/C18 - ENTER THE DRAGON/", },
						{ SongPath = "/Songs/POI-database/C19 - STORM/", },
						{ SongPath = "/Songs/POI-database/C20 - TURN AROUND/", },
						{ SongPath = "/Songs/POI-database/C21 - I LOVE YOU BABY/", },
						{ SongPath = "/Songs/POI-database/C22 - UP UP/", },
						{ SongPath = "/Songs/POI-database/C41 - -REMIX- TRY TO B.P.M. - LIADZ/", },
						{ SongPath = "/Songs/POI-database/C42 - -REMIX- ZERO K HIP-HOP MIX/", },
						{ SongPath = "/Songs/POI-database/C43 - -REMIX- ZERO K HOUSE MIX/", },
						{ SongPath = "/Songs/POI-database/D01 - WITCH DOCTOR #1/", },
						{ SongPath = "/Songs/POI-database/D02 - ARCH OF DARKNESS/", },
						{ SongPath = "/Songs/POI-database/D03 - CHIMERA/", },
						{ SongPath = "/Songs/POI-database/D14 - 2006 LOVE SONG/", },
						{ SongPath = "/Songs/POI-database/D15 - DO YOU KNOW THAT - OLD SCHOOL/", },
						{ SongPath = "/Songs/POI-database/D16 - GUN ROCK/", },
						{ SongPath = "/Songs/POI-database/D17 - BULLFIGHTING'S SONG/", },
						{ SongPath = "/Songs/POI-database/D18 - UGLY DEE/", },
						{ SongPath = "/Songs/POI-database/D28 - FINAL AUDITION EPISODE 2-1/", },
						{ SongPath = "/Songs/POI-database/D30 - FINAL AUDITION EPISODE 2-2/", },
						{ SongPath = "/Songs/POI-database/D29 - FIRE GAME/", },
						{ SongPath = "/Songs/POI-database/D39 - FIRE GAME -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/D04 - GO BACK/", },
						{ SongPath = "/Songs/POI-database/D05 - FLY/", },
						{ SongPath = "/Songs/POI-database/D06 - ONE NIGHT/", },
						{ SongPath = "/Songs/POI-database/D07 - U INSIDE MY DIM MEMORY/", },
						{ SongPath = "/Songs/POI-database/D08 - FREE!/", },
						{ SongPath = "/Songs/POI-database/D09 - LOVELY/", },
						{ SongPath = "/Songs/POI-database/D10 - TERMINAL DEPOSITORY/", },
						{ SongPath = "/Songs/POI-database/D11 - FOR YOU/", },
						{ SongPath = "/Songs/POI-database/D12 - SNOW DREAM/", },
						{ SongPath = "/Songs/POI-database/D13 - HANDSOME CHARACTER THAT PASS/", },
						{ SongPath = "/Songs/POI-database/D19 - HYUN JIN YOUNG GO JIN YOUNG GO!/", },
						{ SongPath = "/Songs/POI-database/D20 - MY BROTHER IS STREET SINGER/", },
						{ SongPath = "/Songs/POI-database/D21 - SO/", },
						{ SongPath = "/Songs/POI-database/D22 - HOLD THE LINE/", },
						{ SongPath = "/Songs/POI-database/D23 - IT'S THE HYBS/", },
						{ SongPath = "/Songs/POI-database/D24 - THROW 'EM UP/", },
						{ SongPath = "/Songs/POI-database/D25 - BUST BACK/", },
						{ SongPath = "/Songs/POI-database/D26 - HALEY/", },
						{ SongPath = "/Songs/POI-database/D27 - WE GOING' FLY REMIX/", },
						{ SongPath = "/Songs/POI-database/D34 - -REMIX- WI-EX-DOC-VA/", },
						{ SongPath = "/Songs/POI-database/D35 - -REMIX- BEMERA/", },
						{ SongPath = "/Songs/POI-database/D36 - -REMIX- BANYA P CLASSIC MIX/", },
						{ SongPath = "/Songs/POI-database/D31 - -REMIX- K-POP DANCE/", },
						{ SongPath = "/Songs/POI-database/D32 - -REMIX- GROOVE PARTY/", },
						{ SongPath = "/Songs/POI-database/D33 - -REMIX- POP HOUSE MIX/", },
						{ SongPath = "/Songs/POI-database/D37 - -REMIX- CHICAGO CLUB MIX/", },
						{ SongPath = "/Songs/POI-database/D41 - LOVE IS A DANGER ZONE 2 -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/D42 - BEAT OF THE WAR 2 -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/D38 - U INSIDE MY DIM MEMORY -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/D40 - LOVELY -FULL SONG-/", },
						{ SongPath = "/Songs/POI-database/D43 - HOLD THE LINE -FULL SONG-/", },
					},
				},
			},
		},
	}
end