function Database_POI()
	return {
		-- playlist 1
		{	Name = "Legacy Korean exclusives",
			Banner = "Playlists/001-legacykor.png",
			Description = "Description for -Legacy Korean exclusives-",
			StartingSublist = 1,
			Sublists = {
			-- sublist 1
				{	Name = "Exclusive charts from Pump It Up The 2nd Dance Floor",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "2ND-DOUBLE" } },
					},
				},
			-- sublist 2
				{	Name = "Exclusive charts from Pump It Up O.B.G The 3rd Dance Floor",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/112 - ANOTHER TRUTH/", Charts = { "3RD-NORMAL", "3RD-HARD" } },
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "3RD-DOUBLE" } },
					},
				},
			-- sublist 3
				{	Name = "Exclusive charts from Pump It Up O.B.G Season Evolution",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/408 - KISS/", Charts = { "OBGSE-NORMAL", "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
					},
				},
			-- sublist 4
				{	Name = "Exclusive charts from Pump It Up Extra",
					StartingSong = 7,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/205 - EXTRAVAGANZA/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/303 - TURKEY MARCH/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/405 - MR. LARPUS/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/505 - BEETHOVEN VIRUS/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/511 - UNFORGETTABLE MEMORY/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/516 - SLAM/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/922 - FINAL AUDITION EPISODE 1/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/915 - LONER/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/916 - MONKEY MAGIC/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/904 - TRASH MAN/", Charts = { "EXTRA-XXDOUBLE" } },
						{ SongPath = "/Songs/POI-database/923 - FIRST LOVE (TECHNO MIX)/", Charts = { "EXTRA-XXPERT", "EXTRA-XXDOUBLE" } },
					},
				},
			-- sublist 5
				{	Name = "Exclusive Korean remixes",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/116 - -REMIX- 1ST DIVA REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/117 - -REMIX- 1ST DISCO REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/118 - -REMIX- 1ST TECHNO REMIX/", Charts = { "1ST-HARD" } },
						{ SongPath = "/Songs/POI-database/219 - -REMIX- JO SUNG MO REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/220 - -REMIX- UHM JUNG HWA REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/223 - -REMIX- SM TOWN REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/224 - -REMIX- REPEATORMENT REMIX/", Charts = { "2ND-HARD", "2ND-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/225 - -REMIX- 2ND HIDDEN REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/322 - -REMIX- 3RD O.B.G DIVA REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/323 - -REMIX- PARK MEE KYUNG REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/325 - -REMIX- PARK JIN YOUNG REMIX/", Charts = { "3RD-HARD", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/327 - -REMIX- BANYA HARD REMIX/", Charts = { "3RD-HARD", "3RD-CRAZY", "3RD-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/415 - -REMIX- SECHSKIES REMIX/", Charts = { "OBGSE-HARD", "OBGSE-CRAZY", "OBGSE-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/924 - -REMIX- EXTRA HIP-HOP REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/925 - -REMIX- E-PAK-SA REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/926 - -REMIX- EXTRA DISCO REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/927 - -REMIX- EXTRA DEUX REMIX/", Charts = { "EXTRA-HARD", "EXTRA-DOUBLE" } },
					},
				},
			},
		},
		-- playlist 2
		{	Name = "Premiere Brazil exclusives",
			Banner = "Playlists/002-premierebr.png",
			Description = "Description for -Premiere Brazil exclusives-",
			StartingSublist = 2,
			Sublists = {
			-- sublist 1
				{	Name = "By difficulty: NORMAL",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-NORMAL" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-NORMAL" } },
					},
				},
			-- sublist 2
				{	Name = "By difficulty: HARD",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-HARD" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-HARD" } },
					},
				},
			-- sublist 3
				{	Name = "By difficulty: DOUBLE",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/611 - A CERCA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/612 - DE VOLTA AO PLANETA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/616 - SEMPRE ASSIM/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/613 - PENSAMENTO/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/614 - POPOZUDA ROCK N' ROLL/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/615 - REBOLA NA BOA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/617 - UMA BOMBA/", Charts = { "PRM1-DOUBLE" } },
						{ SongPath = "/Songs/POI-database/618 - VAQUEIRO BOM DEMAIS/", Charts = { "PRM1-DOUBLE" } },
					},
				},
			},
		},
		-- playlist 3
		{	Name = "Exceed S.E exclusives",
			Banner = "Playlists/003-exceedse.png",
			Description = "Description for -Exceed S.E exclusives-",
			StartingSublist = 3,
			Sublists = {
			-- sublist 1
				{	Name = "By difficulty: NORMAL",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-NORMAL" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-NORMAL" } },
					},
				},
			-- sublist 2
				{	Name = "By difficulty: HARD",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-HARD" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-HARD" } },
					},
				},
			-- sublist 3
				{	Name = "By difficulty: CRAZY",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-CRAZY" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-CRAZY" } },
					},
				},
			-- sublist 4
				{	Name = "By difficulty: FREESTYLE",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-FREESTYLE" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-FREESTYLE" } },
					},
				},
			-- sublist 5
				{	Name = "By difficulty: NIGHTMARE",
					StartingSong = 1,
					AllowedSongs = {
						{ SongPath = "/Songs/POI-database/AE01 - A LITTLE LESS CONVERSATION/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE03 - LET'S GROOVE/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE04 - NAME OF THE GAME/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE05 - RAPPER'S DELIGHT/", Charts = { "EXCSE-NIGHTMARE" } },
						{ SongPath = "/Songs/POI-database/AE06 - WALKIE TALKIE MAN/", Charts = { "EXCSE-NIGHTMARE" } },
					},
				},
			},
		},
	}
end